### ISSUE TITLE
gfortran timeout error

### ISSUE THREAD

**Issue by emmales93** [coatless-mac/macrtools#16]
I receive the following error after entering the command macrtools::macos_rtools_install()

Downloading binary:  https://mac.r-project.org/tools/gfortran-12.2-universal.pkg ...
trying URL 'https://mac.r-project.org/tools/gfortran-12.2-universal.pkg'
Content type 'application/octet-stream' length 253585118 bytes (241.8 MB)
=================================
downloaded 164.4 MB

Error in utils::download.file(url, save_location, quiet = !verbose) : 
  download from 'https://mac.r-project.org/tools/gfortran-12.2-universal.pkg' failed
In addition: Warning messages:
1: In utils::download.file(url, save_location, quiet = !verbose) :
  downloaded length 172354158 != reported length 253585118
2: In utils::download.file(url, save_location, quiet = !verbose) :
  URL 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/595898811/b669240a-ba24-4998-8e99-01b0b78651d5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240531%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240531T220733Z&X-Amz-Expires=300&X-Amz-Signature=46e79a1468614e06c851c6cdfe0b3e4890f4ddee61762ca16c053dcae66a1f7f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=595898811&response-content-disposition=attachment%3B%20filename%3Dgfortran-12.2-universal.pkg&response-content-type=application%2Foctet-stream': Timeout of 60 seconds was reached

**Comment by coatless** [comment]
@emmales93 looks like either the CRAN server was briefly down for maintenance when the command tried to download the [`gfortran-12.2-universal.pkg`](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg) or your computer's internet connection was problematic. 

If you re-run the command, then this step should autocomplete. Alternatively, you can directly run:

```r
macrtools::gfortran_install()
```

**Comment by emmales93** [comment]
Thank you, it appears to have been an issue with internet connectivity. Now resolved!

**Comment by coatless** [comment]
Thanks! I'm going to go ahead and close out this issue ticket then.
