### ISSUE TITLE
Manual install fails as well

### ISSUE THREAD

**Issue by adamhsparks** [coatless-mac/macrtools#5]
So I'm really curious.

The installation using the R functions works fine on my M1 MacBook Pro that I have from work, but it won't work on my personal M1 MacBook Air. So I tried the manual instructions and get this message that `Option --strip-level is not supported`.

```bash
sudo mkdir -p /opt/R/arm64/
  sudo tar fxz /tmp/gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz -C /opt/R/arm64/ --strip-level 3
  rm  /tmp/gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz
tar: Option --strip-level is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

I think that both should be set up basically in the same fashion, both are on Ventura 13.2.1.

**Comment by coatless** [comment]
Ewk! That is odd. I'm not sure why `--strip-level` is problematic on an M1. I appreciate the heads up.

To help debug, could you please run in Terminal: 

```bash
# To understand if the M1 Air is in Bash or ZSH
echo $0

# To understand what the version of tar is
tar --version

# To understand where tar is being called from
# could this be related to homebrew? 
which tar
```

There might be more information I need. But, I appreciate it.

**Comment by adamhsparks** [comment]
Ah, I'm using Fish, but tried with Zsh and get the same result.

So here you are, where I tried with Zsh.

```bash
adamsparks@Adams-MacBook-Air ~ % echo $0
-zsh
```

```bash
adamsparks@Adams-MacBook-Air ~ % tar --version
bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 
```


```bash
adamsparks@Adams-MacBook-Air ~ % which tar
/usr/bin/tar
```

**Comment by coatless** [comment]
Huh. That is exactly the same setup that I have... 

What happens if you type in _R_: 

```r
system("
# To understand if the M1 Air is in Bash or ZSH
echo $0

# To understand what the version of tar is
tar --version

# To understand where tar is being called from
# could this be related to homebrew? 
which tar
")
```

Is it routing into `sh`?

**Comment by coatless** [comment]
Re-visiting, the manual documentation had a typo: `--strip-levels` should be `--strip-components`.
