### ISSUE TITLE
Problems installing gfortran through macrtools

### ISSUE THREAD

**Issue by TomasAPalma** [coatless-mac/macrtools#9]
Hi,

Since yesterday I have been experiencing some problems with rstan R package — every time I try to fit a model using brms I get this error “Error in unserialize(socklist[[n]]) : error reading from connection” — and while trying to understand this issue I discovered this wonderful page of great resources! Thanks!

I thought the problem could be related to the gfortran installation (although it was working nicely a few days), and decided to try out macrtools. I have a arm64 macbook pro.  I had no problems installing macrtools but when I run 

> macrtools::is_gfortran_installed()

It tells me I don't gfortran installed, however when I check on Terminal I get this message:

GNU Fortran (GCC) 11.0.0 20201205 (experimental)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

If I try to install gfortran via macrtools I get this message:

Unable to install gfortran for arm64/aarch64... 
Official R support for arm64/aarch64 began in R 4.1 ...
Please upgrade R ...

The problem is that apparently I have latest R version:

R version 4.3.0 (2023-04-21) -- "Already Tomorrow"

Any idea what is going on here? I am so frustrated because I am not finding for all this mess and I do need to use brms again. 

Thanks so much!
Tomás

**Comment by NadineKJHA** [comment]
Same issue with installing gfortran 

platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.0                         
year           2023                        
month          04                          
day            21                          
svn rev        84292                       
language       R                           
version.string R version 4.3.0 (2023-04-21)
nickname       Already Tomorrow

**Comment by coatless** [comment]
Thanks! You should be able to download it now for R 4.3.0. You can try with:

```r
# install.packages("remotes")
remotes::install_github("coatless-mac/macrtools")
macrtools::gfortran_install()
```

**Comment by NadineKJHA** [comment]
Thanks a lot! The problem is solved
